version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_ml
    environment:
      DB_HOST: aws-1-sa-east-1.pooler.supabase.com
      DB_PORT: 6543
      DB_USER: postgres.ezchuppodybddecvzxht
      DB_PASSWORD: Mars2905@123
      DB_NAME: postgres
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge
