"""Initial migration: tablas anime, manga, personajes

Revision ID: 74aca7dd735c
Revises: 
Create Date: 2026-03-04 15:56:36.959039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aca7dd735c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_english', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=True)
    op.create_table('manga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_english', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_mal_id'), 'manga', ['mal_id'], unique=True)
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=False),
    sa.Column('registros_guardados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_kanji', sa.String(length=255), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personajes_mal_id'), 'personajes', ['mal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personajes_mal_id'), table_name='personajes')
    op.drop_table('personajes')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    op.drop_index(op.f('ix_manga_mal_id'), table_name='manga')
    op.drop_table('manga')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
